log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

  flower:
    address: ':5555'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'ducode@outlook.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      # Remove the IP address from the Host rule
      rule: 'Host(`abejorralmuchopueblo.com`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    # Add a separate router for IP access (without TLS)
    web-insecure-router:
      rule: 'Host(`44.233.206.60`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    flower-secure-router:
      rule: 'Host(`abejorralmuchopueblo.com`)'
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
